{% set name = "qstylizer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/blambright/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 344fef12a7ac2546853ffdf1ef7055aea3b50e41cf469caf71eb4d2acabf42d7

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
    - pbr
  run:
    - python >=3.6
    - tinycss2 >=1.1.0,<2.0
    - inflection >0.3.0,<1.0


test:
  imports:
    - qstylizer
    - qstylizer.style

about:
  home: https://github.com/blambright/qstylizer
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Qt stylesheet generation utility for PyQt/PySide '
  description: |
    qstylizer is a python package designed to help with the construction of
    PyQt/PySide stylesheets.
  doc_url: http://qstylizer.readthedocs.io
  dev_url: https://github.com/blambright/qstylizer

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - steff456
